package ca.app.integration.type;

public enum EventType {
    SUBSCRIPTION_ORDER,
    SUBSCRIPTION_CHANGE,
    SUBSCRIPTION_CANCEL,
    SUBSCRIPTION_NOTICE,
    USER_ASSIGNMENT,
    USER_UNASSIGNMENT,
    USER_SYNC,
    USER_LINK,
    ACCOUNT_SYNC,
    ACCOUNT_UNSYNC,
    ADDON_ORDER,
    ADDON_CHANGE,
    EventType, ADDON_CANCEL
}
